const quotes = [
    { text: "If death strikes before I prove my blood, I swear I'll kill death.", author: "Capt. Manoj Kumar Pandey" },
    { text: "Only the best of friends and the worst of enemies visit us.", author: "Indian Army" },
    { text: "Sleep peacefully at your homes. Indian Army is guarding the frontiers.", author: "Indian Army" },
    { text: "I won't die in an accident or die of any disease. I will go down in glory.", author: "Major Sudhir Kumar Walia" },
    { text: "We fight to win and win with a knockout because there are no runners-up in war.", author: "General J.J. Singh" },
    { text: "सेवा परमो धर्मः (Service is our prime duty)", author: "Sanskrit Proverb" },
    { text: "बलिदानं वीर लक्षणम् (Sacrifice is a characteristic of the brave)", author: "Sanskrit Proverb" },
    { text: "वीर भोग्य वसुंधरा (The brave shall inherit the earth)", author: "Sanskrit Proverb" },
    { text: "पराक्रमो विजयते (Valour triumphs)", author: "Sanskrit Proverb" },
    { text: "The Navy can lose us the war, but only the Air Force can win it.", author: "General Carl A. Spaatz" },
    { text: "I regret I have but one life to give for my country.", author: "Prem Ramchandani" },
    { text: "नभः स्पृशं दीप्तम् (Touch the sky with glory)", author: "Indian Air Force Motto" },
    { text: "Let us celebrate with pride the service rendered to the nation by our fearless and selfless warriors — The Men in White.", author: "Indian Navy" },
    { text: "I have not yet begun to fight!", author: "Captain John Paul Jones" },
    { text: "शं नो वरुणः (May the Lord of the oceans be auspicious unto us)", author: "Indian Navy Motto" },
    { text: "Serve with Honour, Lead with Courage.", author: "IMA/OTA" },
    { text: "Train hard, fight easy.", author: "IMA/OTA" },
    { text: "The more you sweat in peace, the less you bleed in war.", author: "IMA/OTA" },
    { text: "Duty unto death.", author: "BSF" },
    { text: "First line of defense.", author: "BSF" },
    { text: "Protection and Security.", author: "CISF" },
    { text: "Valour, Determination, Devotion.", author: "ITBP" },
    { text: "Balasya Mulam Vigyanam (Strength's Origin is in Science)", author: "DRDO" },
    { text: "We make the sky safer.", author: "HAL" },
    { text: "Space is our playground.", author: "ISRO" },
    { text: "Touching the stars with Indian hands.", author: "ISRO" },
    { text: "You don’t join the forces for money or comfort. You do it for pride, honor, and duty.", author: "Unknown" },
    { text: "Courage is not the absence of fear, but the triumph over it. That’s what makes a soldier.", author: "Indian Army Aspirants" },
    { text: "Dream to wear the uniform, train to deserve it.", author: "Defense Aspirant" },
    { text: "Every drop of sweat today saves a drop of blood tomorrow.", author: "Military Saying" },
    { text: "The uniform doesn’t just protect the country, it builds the man.", author: "Defense Enthusiast" },
    { text: "In service of the nation, even a moment of hesitation is a disservice.", author: "Defense Philosophy" },
    { text: "Tough times create strong soldiers. You’re one of them.", author: "Motivational Saying" },
    { text: "The day you stop complaining is the day you start leading.", author: "Army Mindset" },
    { text: "The true soldier fights not because he hates what is in front of him, but because he loves what is behind him.", author: "G.K. Chesterton" },
    { text: "A soldier doesn't give up when he's tired. He gives up when he's done.", author: "Indian Defense Spirit" },
    { text: "For every civilian’s sleep, a jawan sacrifices his own.", author: "Indian Armed Forces" },
    { text: "To lead a nation, first learn to serve it.", author: "Civil Service Motivation" },
    { text: "IAS is not a job, it’s a journey of responsibility.", author: "Civil Service Community" },
    { text: "IPS: Fearless in action, flawless in duty.", author: "Law Enforcement Pride" },
    { text: "The dream is not to wear the stars on shoulders, but to earn them.", author: "Defense & Civil Service Aspirants" },
    { text: "I wonder whether those of our political masters who have been put in charge of the defence forces can distinguish a mortar from a motor; a gun from a howitzer; a guerrilla from a gorilla, although a great many resemble the latter.", author: "Field Marshal Sam Manekshaw" },
    { text: "There will be no withdrawal without written orders and these orders shall never be issued.", author: "Field Marshal Sam Manekshaw" },
    { text: "I don’t care if a soldier is a Hindu, Muslim, Christian or Parsi. He is a soldier. His religion is his rifle.", author: "Field Marshal Sam Manekshaw" },
    { text: "Discipline and united action are the real source of strength for the nation.", author: "Field Marshal K.M. Cariappa" },
    { text: "The safety, honour and welfare of your country come first, always and every time.", author: "Field Marshal K.M. Cariappa" },
    { text: "I have no caste, no religion. I live and die for the Indian Army.", author: "Field Marshal K.M. Cariappa" },
    { text: "It was not easy building the Air Force from scratch, but we were fueled by vision and service.", author: "Air Chief Marshal Subroto Mukerjee" },
    { text: "A soldier who fights to uphold peace is stronger than a thousand who fight for power.", author: "Air Chief Marshal Subroto Mukerjee" }
  ];
  
  
  export default quotes;